exports.DroneModel = {
  LIGHT_WEIGHT: "LIGHT_WEIGHT",
  MIDDLE_WEIGHT: "MIDDLE_WEIGHT",
  CRUISER_WEIGHT: "CRUISER_WEIGHT",
  HEAVY_WEIGHT: "HEAVY_WEIGHT",
};

exports.DroneState = {
  IDLE: "IDLE",
  LOADING: "LOADING",
  LOADED: "LOADED",
  DELIVERING: "DELIVERING",
  DELIVERED: "DELIVERED",
  RETURNING: "RETURNING",
};




